services:
  nginx:
    image: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./src:/var/www/montedakou.net/
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/montedakou.conf:/etc/nginx/conf.d/default.conf:ro
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    depends_on:
      - php
    networks:
      - webnet

  php:
    image: php:8.3-fpm-alpine
    volumes:
      - ./src:/var/www/montedakou.net
    networks:
      - webnet

  icecast2:
    image: moul/icecast
    ports:
      - "8000:8000"
    volumes:
      - ./icecast/icecast.xml:/etc/icecast2/icecast.xml
    networks:
      - webnet
    restart: unless-stopped

networks:
  webnet:
    driver: bridge